name: Build (Windows-ORT)

on: [push, workflow_dispatch]

jobs:
  build-windows:
    runs-on: windows-2019

    defaults:
      run:
        shell: cmd
        working-directory: vsort

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Setup Ninja
      run: pip install ninja

    - name: Cache protobuf
      id: cache-protobuf
      uses: actions/cache@v2
      with:
        path: vsort/protobuf/install
        key: ${{ runner.os }}-vsort-protobuf-v1

    - name: Checkout protobuf
      uses: actions/checkout@v2
      if: steps.cache-protobuf.outputs.cache-hit != 'true'
      with:
        repository: protocolbuffers/protobuf
        # if you change this, remember to bump the version of the cache key.
        ref: v3.16.0
        fetch-depth: 1
        path: vsort/protobuf

    - name: Configure protobuf
      if: steps.cache-protobuf.outputs.cache-hit != 'true'
      run: cmake -S protobuf\cmake -B protobuf\build_rel -G Ninja -LA
        -D CMAKE_BUILD_TYPE=Release
        -D protobuf_BUILD_SHARED_LIBS=OFF  -D protobuf_BUILD_TESTS=OFF

    - name: Build protobuf
      if: steps.cache-protobuf.outputs.cache-hit != 'true'
      run: cmake --build protobuf\build_rel --verbose

    - name: Install protobuf
      if: steps.cache-protobuf.outputs.cache-hit != 'true'
      run: cmake --install protobuf\build_rel --prefix protobuf\install

    - name: Cache onnx
      id: cache-onnx
      uses: actions/cache@v2
      with:
        path: vsort/onnx/install
        key: ${{ runner.os }}-vsort-onnx-v1

    - name: Checkout onnx
      if: steps.cache-onnx.outputs.cache-hit != 'true'
      uses: actions/checkout@v2
      with:
        repository: onnx/onnx
        # follows onnx in https://github.com/AmusementClub/onnxruntime/tree/github-actions/cmake/external
        # if you change this, remember to bump the version of the cache key.
        ref: be76ca7148396176784ba8733133b9fb1186ea0d
        fetch-depth: 1
        path: vsort/onnx

    - name: Configure onnx
      if: steps.cache-onnx.outputs.cache-hit != 'true'
      run: cmake -S onnx -B onnx\build -G Ninja -LA
        -D CMAKE_BUILD_TYPE=Release
        -D Protobuf_PROTOC_EXECUTABLE=protobuf\install\bin\protoc
        -D Protobuf_LITE_LIBRARY=protobuf\install\lib
        -D Protobuf_LIBRARIES=protobuf\install\lib
        -D ONNX_USE_LITE_PROTO=ON -D ONNX_USE_PROTOBUF_SHARED_LIBS=OFF
        -D ONNX_GEN_PB_TYPE_STUBS=OFF -D ONNX_ML=0
        -D ONNX_USE_MSVC_STATIC_RUNTIME=1

    - name: Build onnx
      if: steps.cache-onnx.outputs.cache-hit != 'true'
      run: cmake --build onnx\build --verbose

    - name: Install onnx
      if: steps.cache-onnx.outputs.cache-hit != 'true'
      run: cmake --install onnx\build --prefix onnx\install

    - name: Download VapourSynth headers
      run: |
        curl -s -o vs.zip -L https://github.com/vapoursynth/vapoursynth/archive/refs/tags/R54.zip
        unzip -q vs.zip
        mv vapoursynth-*/ vapoursynth/

    - name: Download ONNX Runtime Precompilation
      run: |
        curl -s -o ortgpu.zip -LJO https://github.com/AmusementClub/onnxruntime/releases/latest/download/onnxruntime-gpu-win64.zip
        unzip -q ortgpu.zip

    - name: Configure
      run: cmake -S . -B build -G Ninja -LA
        -D CMAKE_BUILD_TYPE=Release
        -D CMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded
        -D VAPOURSYNTH_INCLUDE_DIRECTORY=vapoursynth\include
        -D protobuf_DIR=protobuf\install\cmake
        -D ONNX_DIR=onnx\install\lib\cmake\ONNX
        -D ONNX_RUNTIME_API_DIRECTORY=onnxruntime-gpu\include\onnxruntime\core\session
        -D ONNX_RUNTIME_LIB_DIRECTORY=onnxruntime-gpu\lib

    - name: Build
      run: cmake --build build --verbose

    - name: Install
      run: |
        cmake --install build --prefix install
        mkdir artifact
        mkdir artifact\vsort
        copy install\bin\vsort.dll artifact\
        copy onnxruntime-gpu\bin\*.dll artifact\vsort\
        copy onnxruntime-gpu\lib\*.dll artifact\vsort\

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: VSORT-Windows-x64
        path: vsort/artifact
